name: CI

on:
  push:
    branches:
      - main

jobs:
  steps:

    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile.production
        push: false
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodos_app:latest

    - name: Run tests
      run: make test

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile.production
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodos_app:latest
